@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(LB, "Reverse proxy", "Nginx", "")
Container(api, "API Gateway", "Java")
Container(api, "API Gateway", "Java")


System_Boundary(CommentSystem, "Comment system") {
Container(CommentService, "Comment Service", "Java", "Gets and save comments")
ContainerDb(CommentDb, "Comment database", "PG", "Store comments")
}


Rel(user, LB, "Create/delete comment; Gets comments", "REST")
Rel(LB, api, "Create/delete comment; Gets comments", "REST")
Rel(api, CommentService, "Create/delete comment; Gets comments", "REST")
Rel(CommentService, CommentDb, "Create/delete comment by post; Gets comments")
@enduml