@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(LB, "Reverse proxy", "Nginx", "")
Container(api, "API Gateway", "Java")
Container(api, "API Gateway", "Java")
ContainerQueue(EventQ, "Event queue", "Kafka", "Post events")
Container(FeedSystem, "Feed System", "Software system", "Store feeds")
Container(MediaSystem, "Media System", "Software system", "Store and save photos, generate secure url")
Container(ReactionSystem, "Reaction System", "Software system", "Store and count likes")
Container(CommentSystem, "Comment System", "Software system", "Store and save comments")


System_Boundary(PostSystem, "Post system") {
Container(PostService, "Post Service", "Java", "Saves post, creates event of post'")
ContainerDb(PostDb, "Post database", "PG", "Store and save posts")
}


Rel(user, LB, "Create/delete post", "REST")
Rel(LB, api, "Create/delete post", "REST")
Rel(api, PostService, "Create/delete post", "REST")
Rel(PostService, PostDb, "Create/delete post")
Rel(PostService, EventQ, "Send post, event 'Post is created/deleted'")
Rel(FeedSystem, PostService, "Gets posts", "REST")
Rel(FeedSystem, EventQ, "Subscribes on posts events (for manage feeds)")
Rel(MediaSystem, EventQ, "Subscribes on posts events (for manage photos or deleted photos by post)")
Rel(ReactionSystem, EventQ, "Subscribes on posts events (for create reaction_value = 0 or deleted reactions by post)")
Rel(CommentSystem, EventQ, "Subscribes on posts events (for deleted comments by post)")

@enduml